spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/user_db?allowPublicKeyRetrieval=true&useSSL=false
    username: woorinpang_user
    password: woorinpang_pass
    driver-class-name: org.mariadb.jdbc.Driver

woorinpang:
  application: user-service-default